<?php
//prepare useful variables
$translation_map = $filter_config['zh'];
?>

<link href="/css/product/detail.css" rel="stylesheet" type="text/css" media="screen"></link>
<link href="http://cdn.xiyouus.com/css/datepicker.css" rel="stylesheet" type="text/css" media="screen"></link>
<link rel="stylesheet" type="text/css" href="/css/jquery-ui.css" />
<link rel="stylesheet" type="text/css" href="/css/jquery-ui.theme.css" />
<link rel="stylesheet" type="text/css" href="/css/jquery-ui.structure.css" />
<script src="/js/jquery-ui.js"></script>
<script src="/js/miniPriceCalendar.js"></script>
<script src="/js/product/detail.js"></script>
<div class="dian">
    <div class="zhizhao">当前位置：<a href="/">西游迹首页</a> > <a href="">产品详情</a></div>
    <!--code start-->
    <div class="mybox">
        <div class="line1 clearfix">
            <div class="pull-left jdslide">
                <!--slide start-->
                <div class="game163">
                    <ul class="bigImg list-unstyled">
                        <li><a><img src="<?php echo \Product\Util\ServiceUtil::generateProductImgUrl($product['product_id'], '1', false); ?>" /></a></li>
                        <li><a><img src="<?php echo \Product\Util\ServiceUtil::generateProductImgUrl($product['product_id'], '2', false); ?>" /></a></li>
                        <li><a><img src="<?php echo \Product\Util\ServiceUtil::generateProductImgUrl($product['product_id'], '3', false); ?>" /></a></li>
                        <li><a><img src="<?php echo \Product\Util\ServiceUtil::generateProductImgUrl($product['product_id'], '4', false); ?>" /></a></li>
                    </ul>
                    <div class="smallScroll">
                        <div class="smallImg">
                            <ul class="list-unstyled">
                                <li><a><img src="<?php echo \Product\Util\ServiceUtil::generateProductImgUrl($product['product_id'], '1', false); ?>" /></a></li>
                                <li><a><img src="<?php echo \Product\Util\ServiceUtil::generateProductImgUrl($product['product_id'], '2', false); ?>" /></a></li>
                                <li><a><img src="<?php echo \Product\Util\ServiceUtil::generateProductImgUrl($product['product_id'], '3', false); ?>" /></a></li>
                                <li><a><img src="<?php echo \Product\Util\ServiceUtil::generateProductImgUrl($product['product_id'], '4', false); ?>" /></a></li>
                            </ul>
                        </div>
                    </div>
                </div>
                <!--                <div class="arrowbg"></div>-->
                <!--slide over--->
            </div>
            <div class="pull-right thedetail">
                <h1 id="title"><?php echo $product['title']; ?></h1>
                <input id="product_id" value="<?php echo $product['product_id']; ?>" hidden>
                <div class="thedetail_box">
                    <!--<div class="starcomment">行程评价(6)：<img src="http://cdn.xiyouus.com/img/star4.jpg"></div>-->
                    <table class="table">
                        <tr>
                            <td width="80">产品编号：</td>
                            <td><?php echo $product['product_id']; ?></td>
                        </tr>
                        <tr>
                            <td>西游售价：</td>
                            <td class="clearfix">
                                <div class="oldprice pull-left"><b><?php echo round($product['low_price'] / 100 * 1.05); ?></b>/人起</div>
                                <div class="newprice pull-left"><b><?php echo $product['low_price'] / 100; ?></b>/人起</div>
                                <a class="qjinfo pull-left" href="#price_detail" data-toggle="tooltip" data-placement="bottom" title="此价格是三人或者四人同住双人房的最低人均价格。 价格会根据所选房型,额外行程及活动等产生变化">起价说明</a>
                            </td>
                        </tr>
                        <tr>
                            <td>行程天数：</td>
                            <td><?php echo $translation_map['duration'][$product['duration']]; ?></td>
                        </tr>
                        <tr>
                            <td>出发时间：</td>
                            <td><?php
                                //TODO what if there are several start date
                                echo $product['start_date']
                                ?></td>
                        </tr>
                        <tr>
                            <td>出发地点：</td>
                            <td><?php echo $translation_map['place'][$product['startCity']]; ?> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;离团地点： <?php echo $translation_map['place'][$product['endCity']]; ?></td>
                        </tr>
                        <tr>
                            <td>参观景点：</td>
                            <td>
                                <ul class="visitul list-unstyled list-inline">
                                    <?php
                                    $included_place = explode(';', $product['includedPlace']);
                                    foreach ($included_place as $aplace) {
                                        if ($aplace != 0) {
                                            echo '<li>';
                                            echo $translation_map['place'][$aplace];
                                            echo '</li>';
                                        }
                                    }
                                    //TODO implement clickable place page
//                                         <li class="longli">高进北出垦丁大街</li>
                                    ?>
                                </ul>
                            </td>
                        </tr>
                    </table>
                </div>
            </div><!--pull-right over--->
        </div><!--line1 over-->
        <hr>
        <div class="line2 clearfix">
            <div class="pull-left chosedate">
                <form id="detailForm">
                    <input name="product_id" value="<?php echo $product['product_id']; ?>" hidden>
                    <div id="dp3" class="input-append date">
                        <table>
                            <tr>
                                <td>出发日期：</td>
                                <td><input name="from" class="form-control input-sm dp-input" pdid="<?php echo $product['product_id']; ?>" pduration="<?php echo $product['duration']; ?>" type="text"  value="" size="16"></td>
                            </tr>
                            <tr>
                                <td>结束日期：</td>
                                <td><span id="end_date_val">&nbsp;</span></td>
                            </tr>
                        </table>
                    </div>
                    <div class="choosebox">
                        <table id="roomArea" class="table table-condensed chooseboxtable">
                            <tr>
                                <td class="text-right">选择房间</td>
                                <td><select id="numRoom" name="numRoom" class="form-control input-sm" onchange="onRoomChange()">
                                        <option>1</option>
                                        <option>2</option>
                                        <option>3</option>
                                        <option>4</option>
                                        <option>5</option>
                                        <option>6</option>
                                        <option>7</option>
                                        <option>8</option>
                                        <option>9</option>
                                    </select></td>
                                <td colspan="1">&nbsp;</td>
                                <td><span>&nbsp;</span></td>
                            </tr>

                            <tr class="d_rm">
                                <td class="text-right">房间 1</td>
                                <td>
                                    <select class="form-control input-sm">
                                        <option>成人</option>
                                    </select>
                                </td>
                                <td>
                                    <select class="form-control input-sm">
                                        <option>儿童</option>
                                    </select>
                                </td>
<!--                                <td>
                                    <select class="form-control input-sm">
                                        <option>床型</option>
                                        <option value="2">双床房</option>
                                        <option value="1">大床房</option>
                                    </select>
                                </td>-->
                            </tr>


                        </table>
<!--                        <table style="margin-left:28px;">
                            <tr>
                                <td class="text-right">酒店升级&nbsp;&nbsp;</td>
                                <td colspan="2">
                                    <select class="form-control input-sm">
                                        <option>无需升级</option>
                                    </select>
                                </td>
                                <td colspan="2">&nbsp;</td>
                            </tr>
                            <tr>
                                <td>&nbsp;</td>
                            </tr>
                            <tr>
                                <td class="text-right">机场接送&nbsp;&nbsp;</td>
                                <td colspan="2">
                                    <select class="form-control input-sm">
                                        <option>无需接送</option>
                                    </select>
                                </td>
                                <td colspan="2">&nbsp;</td>
                            </tr>
                        </table>-->
                    </div><!--choosebox over-->
                </form>
            </div><!--left over-->

            <div class="pull-right orderpricebox">
                <table class="table">
                    <tr>
                        <td><b>总&nbsp;&nbsp;&nbsp;价</b></td>
                        <td>美元：$ <i id="totalPrice">N/A</i> 人民币：￥ <i id="totalPriceRmb">N/A</i></td>
                    </tr>
                    <tr>
                        <td><b>人均价</b></td>
                        <td>美元：$ <i id="unitPrice">N/A</i> 人民币：￥ <i id="unitPriceRmb">N/A</i></td>
                    </tr>
                    <tr>
                        <td colspan="2" class="text-center">
                            <ul class="orderbuyul list-unstyled list-inline">
                                <li class="ordernow mouse_pointer"onclick="place_order(<?php echo $product['product_id']; ?>)" >立即预定</li>
                                <li class="tocart mouse_pointer" onclick="add_cart(<?php echo $product['product_id']; ?>)">放入购物车</li>
                            </ul>
                        </td>
                    </tr>
                    <tr>
                        <td colspan="2">
                            <?php
                            $promo_arr = explode(';', $product['promo']);
                            if (count($promo_arr) > 1) {
                                foreach ($promo_arr as $aPromo) {
                                    if ($aPromo > 0) {
                                        echo '<a style="margin-left:20px;"><img src="'
                                        . $translation_map['promo_url'][$aPromo]
                                        . '">';
                                        echo $translation_map['promo'][$aPromo]
                                        . '</a>';
                                    }
                                }
                            }
                            ?>
                        </td>
                    </tr>
                </table>
            </div><!--right over-->
        </div><!--line2 over-->
        <div class="line3">
            <ul class="list-unstyled list-inline tabdetail">
                <li class="current">产品详情</li>
                <li>费用明细</li>
                <li>注意事项</li>
                <!--<li>常见问题</li>-->
                <li>快速提问</li>
                <li>团友评价</li>
                <li>倾情推荐</li>
            </ul>
            <!--daily detail-->
            <div class="tabcontents">
                <div class="tabcontents-title">西游迹倾情介绍完美大礼包</div>
                <p class="tabcontentsp">
                    <?php
                    echo $product_info['special_intro'];
                    ?>
                </p>
                <?php
                $product_daily_detail_str = $product_info['detail_description'];
                $daily_detail_arr = json_decode($product_daily_detail_str, true)['daily_detail'];
                //echo ini_set("display_errors",1);
                $cnt = 1;
                foreach ($daily_detail_arr as $aday_detail) {
                    echo '<h3 class="xcday">第' . $cnt . '天- ' . $aday_detail['t'] . '</h3>';
                    //TODO dynamically display image
                    echo '<div class="xcbox clearfix">
                            <div class="pull-left"><img src="/img/product/' . $product['product_id'] . '/D' . $cnt . '.jpg" width="246" height="152"></div>
                            <div class="pull-right">
                                <p>' . $aday_detail['d'] . '</p>
                            </div>
                        </div>';
                    $cnt++;
                }
                ?>
            </div><!--tabcontents over-->
            <!--daily detail-->
            <div class="tabcontents">
                <h3><a name="price_detail" href="javascript:;">费用明细</a></h3>
                <div class="perprice">每人团费</div>
                <table class="table perpricetable">
                    <tr>
                        <td> 人数 </td>
                        <td>  单人一间(i)  </td>
                        <td> 双人一间(i)  </td>
                        <td> 三人一间(i) </td>
                        <td> 四人一间(i) </td>
                        <td> 儿童 </td>
                    </tr>
                    <tr>
                        <td>  价格 </td>
                        <td id="singleP">  请选择日期 </td>
                        <td id="doubleP">  N/A </td>
                        <td id="tripleP"> N/A </td>
                        <td id="quadP">  N/A </td>
                        <td id="childP">  N/A </td>
                    </tr>
                </table>
                <div class="prop">买二送一价格说明：<br>*总价=单价*2</div>
                <h4>费用包括</h4>
                <table class="table htable">
                    <?php
                    $price_include_arr = explode(';', $product_info['price_include']);
                    if (count($price_include_arr) > 0) {
                        foreach ($price_include_arr as $an_included) {
                            echo '<tr><td>' . $an_included . '</td></tr>';
                        }
                    }
                    ?>
                </table>
                <h4>费用不包括</h4>
                <table class="table htable">
                    <?php
                    $price_not_include_arr = explode(';', $product_info['price_not_include']);
                    if (count($price_not_include_arr) > 0) {
                        foreach ($price_not_include_arr as $a_not_included) {
                            echo '<tr><td>' . $a_not_included . '</td></tr>';
                        }
                    }
//                        $price_not_include_arr = explode(';', $product_info['price_not_include']);
//                        if (count($price_not_include_arr) > 0) {
//                            foreach ($price_not_include_arr as $a_not_included) {
//                                $not_includes = explode('-', $a_not_included);
//                                if (count($not_includes) == 2) {
//                                    echo '<tr>
//                                        <td>' . $not_includes[0] . '</td>
//                                        <td>' . $not_includes[1] . '</td>
//                                    </tr>';
//                                }
//                            }
//                        }
                    ?>
                </table>
            </div><!--tabcontents over-->
            <div class="tabcontents">
                <h3><a href="javascript:;">注意事项</a></h3>
                <table class="table htable">
                    <?php
                    $notice_note_str = $product_info['notice_note'];
                    $notice_arr = explode(';', $notice_note_str);
                    foreach ($notice_arr as $aNotice) {
                        echo '<tr><td>' . $aNotice . '</td></tr>';
                    }
                    ?>
                </table>
                
                <h4>预定程序及电子票</h4>
                <table class="table htable">
                    <tr><td>1. 订购方式：西游迹旅行网目前仅提供网上预订(www.xiyouus.com)和电话预订(美国603-995-1159)两种预订方式。</td></tr>
                    <tr><td>2. 填写订单：选定产品后，在该行程页面选择和填写基本信息，系统会自动为您计算相应的价格。点击“马上预订”或“加入购物车”完成详细的订单信息填写及结算。待您成功下单后西游迹旅行网将给您发送预订邮件，订购者有义务进行详细核对。</td></tr>
                    <tr><td>3. 支付方式：网站目前支持美金和人民币支付，并提供四种付款方式，包括：支付宝、财付通、PayPal和Strip支付。订单支付成功后，您的注册邮箱会立即收到西游迹旅行网给您发送的【订单支付成功】的邮件，订购者有义务再次核对并确保信息正确。</td></tr>
                    <tr><td>4. 确认时长：在您成功支付订单费用之后的1-2个工作日内，我们会给您的注册邮箱发送【订单确认函】。一旦您收到【订单确认函】，即意味着您的订单已经被确认。此时如果您需要更改或取消订单，请参看更改或取消条款。</td></tr>
                    <tr><td>5. 获取【行程确认单】：一旦您的预定得到确认，我们会向您的注册邮箱发送【行程确认单】。在【行程确认单】中，我们会提供您所预定产品的所有详细资讯，包括但不仅限于出发时间、行程、酒店、机场接送、紧急联络电话等信息，请务必打印您的【行程确认单】，并携带有效身份证件参加您所预订的行程。</td></tr>
                </table>

                <h4>订购条例</h4>
                <table class="table htable">
                    <tr>
                        <td><a href="/misc/page/index/">查看西游迹订购条例详情</a></td>
                    </tr>
                </table>
            </div>
            <div class="tabcontents">
                <h3><a href="javascript:;">快速提问</a></h3>
                <table class="table asktable">
                    <tr>
                        <td width="345px" ><a>☆ 您的姓名&nbsp;&nbsp; </a><input id="askName" type="text" class="asktext asksect"><p class="help-block namehelp warninghelp" style="color:red;">请输入您的姓名</p></td>

                        <td><a>☆ 您的EMAIL&nbsp;&nbsp; </a><input id="askEmail" type="text" class="asktext asksect"><p class="help-block emailhelp warninghelp" style="color:red;">请输入正确的邮箱</p></td>
                    </tr>
                    <tr>
                        <td colspan="2">
                            ☆ 您的提问&nbsp;&nbsp; <textarea id="askQuestion" class="asktextarea asksect"></textarea><p class="help-block questionhelp warninghelp" style="color:red;">请输入您的提问内容</p>
                        </td>
                        <td><img src ="/img/questionmark.png"></td>
                    </tr>

                    <tr>
                        <td><a>☆ 验证码&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </a><input name="captcha_ans" id="askCaptcha" type="text" class="asktext asksect"><p class="help-block captchahelp warninghelp" style="color:red;">验证码不正确，请重新输入</p></td>
                        <td>
                            <div id="captcha_table">
                            </div>
                            <div id="hidenDiv" hidden></div>
                            <div class="refresh">
                                <a style="cursor: pointer;" onclick="refreshCaptcha()">&nbsp;换一张?</a>                                      
                            </div>
                        </td>
                        <td><input type="submit" value=""  class="asksubmit" onclick="submitQuestion()"></td>
                    </tr>
                </table>
            </div><!--tabcontents over-->
            <div class="tabcontents">
                <h3><a href="javascript:;">用户评论</a></h3>
                <table class="table htable">
                    <tr>
                        <td>暂无用户评论</td>
                    </tr>
                </table>
            </div><!--tabcontents over-->
            <div class="tabcontents">
                <h3><a>倾情推荐</a></h3>
                <div class="tuijianbox">
                    <div class="row">
                        <?php
                        if (count($recom_product_arr) > 0) {
                            foreach ($recom_product_arr as $aRecomProduct) {
                                //TODO image, href
                                echo '<div class="col-xs-4">
                                            <a href="/product/query/detail/' . $aRecomProduct['product_id'] . '"><div class="tuijian-pic"><img src="/img/product/' . $aRecomProduct['product_id'] . '/thumb.jpg" class="center-block" width="241" height="218"></div>
                                            <div class="tuijian-title center-block text-center">' . $aRecomProduct['title'] . '</div></a>
                                        </div>';
                            }
                        } else {
                            //TODO non-recommondation content
                        }
                        ?>
                    </div>
                </div>
            </div><!--tabcontents over-->
        </div><!--line3 over-->
    </div>
    <!--code over--->
</div>

<script src="http://cdn.xiyouus.com/js/jquery.SuperSlide.2.1.1.js"></script>
<script src="/js/product/detail.js"></script>
<script>
                            jQuery(".game163").slide({titCell: ".smallImg li", mainCell: ".bigImg", effect: "fold", autoPlay: true, delayTime: 200,
                                startFun: function(i, p) {
                                    if (i == 0) {
                                        jQuery(".game163 .sPrev").click()
                                    } else if (i % 4 == 0) {
                                        jQuery(".game163 .sNext").click()
                                    }
                                }
                            });
                            jQuery(".game163 .smallScroll").slide({mainCell: "ul", delayTime: 100, vis: 4, scroll: 4, effect: "left", autoPage: true, prevCell: ".sPrev", nextCell: ".sNext", pnLoop: false});
</script>
<script>
    $(document).ready(function() {
        $('.qjinfo').tooltip();
    })
</script>
<script>
    $('.tabdetail li').click(function() {
        var el_index = $(this).parent().find('li').index(this);
        $(this).parent().find('li').removeClass('current');
        $(this).addClass('current');
        $(this).parent().parent().find("div.tabcontents").hide();
        $(this).parent().parent().find("div.tabcontents").eq(el_index).show();

    });
</script>