<?php echo $this->doctype(); ?>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php $this->headTitle('西游迹DIY')->setAutoEscape(true); ?>
        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>
        <meta name="title" content="西游迹旅行，创意出国游-xiyouus.com">
        <meta name="description" content="西游迹旅行网（xiyouus.com），隶属于美国Global Traveler旅行集团，专注于自由创意的出国旅行，让您的异国之旅不再单调。西游迹提供的特色服务包括定制自由行、超值跟团游、有机农场工作换食宿、租车自驾游、邮轮滑翔跳伞射击等深度游玩项目。">
        <meta name="author" content="西游迹旅行网-xiyouus.com">
        <meta name="keywords" content="西游迹旅行,美国旅游,美国自助游,美国旅行公司,黄石公园旅游,美国当地华人旅行">
        <meta name="360-site-verification" content="9420c19bc751c73578ef4fd218c63fca" />
        <meta property="qc:admins" content="551357352175536375" />

        <!-- Le styles -->
        <?php
        echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => 'http://cdn.xiyouus.com/img/favicon.ico'))
                ->prependStylesheet('http://cdn.xiyouus.com/style/style.css')
                ->prependStylesheet('http://cdn.xiyouus.com/style/common.css')
                ->prependStylesheet('http://cdn.xiyouus.com/css/bootstrap.min.css')
                ->prependStylesheet('http://cdn.xiyouus.com/css/product/list.css');
        ?>

        <!-- Scripts -->
        <?php
        echo $this->headScript()->prependFile('http://cdn.xiyouus.com/js/html5shiv.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                ->prependFile('http://cdn.xiyouus.com/js/product/productlist.js', 'text/javascript')
                ->prependFile('http://cdn.xiyouus.com/js/product/search.js', 'text/javascript')
                ->prependFile('http://cdn.xiyouus.com/js/common.js', 'text/javascript')
                ->prependFile('http://cdn.xiyouus.com/js/bootstrap.min.js')
                ->prependFile('http://cdn.xiyouus.com/js/jquery.min.js');
        ?>

    </head>
    <body>
        <!--navbar-->
        <div class="dao">
            <div class="hang clearfix">
                <div class="logo pull-left"><img src="http://cdn.xiyouus.com/img/logo.png" /></div>
                <ul class="shou pull-left">
                    <li><a href="">首页</a></li>
                    <!--TODO dynamic highlight-->
                    <li class="beimei"><a href="">北美旅游</a></li>
                </ul>
                <ul class="deng pull-right">
                    <li><a href="">登录</a></li>
                    <li><a href="">注册</a></li>
                    <li class="gou"><a href="">购物车</a></li>
                    <li class="ding"><a href="">订单查询</a></li>
                </ul>
            </div>
        </div>
        <!--navbar-->
        <!--main-->
        <div class="wai">
            <div class="zhong clearfix">
                <?php echo $this->content; ?>
            </div>
        </div>
        <!--main-->
        <!--footer-->
        <div class="dibu">
            <div class="zhii">
                <div class="kki">© 2010-2014 xiyouus.com</div>
                <div class="kki">营业执照注册号 ：111111111111111111     许可证：88888888888888</div>
            </div>
        </div>
        <!--footer-->
        <?php echo $this->inlineScript() ?>
    </body>
</html>
