<?php echo $this->doctype(); ?>
<html lang="zh">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle(htmlspecialchars('GoTrip'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <!-- Le styles -->
        <?php
        echo $this->headLink(array('rel' => 'shortcut icon', 'href' => 'http://cdn.xiyouus.com/img/favicon.png'))
                ->prependStylesheet('/style/style.css')
                ->prependStylesheet('http://cdn.xiyouus.com/style/common.css')
                ->prependStylesheet('http://cdn.xiyouus.com/css/bootstrap.min.css');
        ?>

        <!-- Scripts -->
        <?php
        echo $this->headScript()->prependFile('http://cdn.xiyouus.com/js/html5shiv.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                ->prependFile('/js/common.js', 'text/javascript')
                ->prependFile('http://cdn.xiyouus.com/js/bootstrap.min.js')
                ->prependFile('http://cdn.xiyouus.com/js/jquery.min.js');
        ?>
        <!--[if lt IE 9]>
        <script src="js/respond.min.js"></script>
        <![endif]-->
    </head>
    <body>
        <!--main-->
        <div class="mainContainer">
            <?php echo $this->content; ?>
        </div>
        <!--main-->
        <!--footer-->
        <?php require __DIR__ . '../../../../Libraries/view/include/footer.php'; ?>
        <!--footer-->
        <?php echo $this->inlineScript() ?>
    </body>
</html>
