<!DOCTYPE html>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->
<html>
<head>
<title>邮件</title>
<meta http-equiv="Content-Type" content="text/html; charset=gb2312">
</head>
<body bgcolor="#FFFFFF" leftmargin="0" topmargin="0" marginwidth="0" marginheight="0">
<!-- Save for Web Slices (wooshi.psd) -->
<table id="__01" width="793" height="1534" border="0" cellpadding="0" cellspacing="0">
<!--	<tr>
		<td colspan="4">
			<img src="/img/wooshi_01.png" width="793" height="59" alt=""></td>
	</tr>-->
	<tr>
		<td rowspan="5">
			<img src="/img/wooshi_02.png" width="61" height="1474" alt=""></td>
		<td>
			<img src="/img/wooshi_03.png" width="676" height="61" alt=""></td>
	</tr>
	<tr>
		<td colspan="2">
			<img src="/img/wooshi_05.png" width="678" height="351" alt=""></td>
	</tr>
	<tr>
		<td colspan="2">
			<img src="/img/wooshi_07.png" width="678" height="504" alt=""></td>
	</tr>
	<tr>
		<td colspan="2">
			<img src="/img/wooshi_08.png" width="678" height="61" alt=""></td>
	</tr>
	<tr>
		<td colspan="2">
			<img src="/img/wooshi_09.png" width="678" height="497" alt=""></td>
	</tr>
</table>
<!-- End Save for Web Slices -->
</body>
</html>