<?php
namespace Product\Util;

class ErrorType
{
	const PARAMETER_NOT_GIVEN = 'PARAMETER_NOT_GIVEN';
	const PARAMETER_OUT_OF_RANGE = 'PARAMETER_OUT_OF_RANGE';
	const PARAMETER_NOT_VALID = 'PARAMETER_NOT_VALID';

	const NOT_AUTHENTICATED = 'NOT_AUTHENTICATED';
	const NOT_ENOUGH_RIGHTS = 'NOT_ENOUGH_RIGHTS';
	
	const PRODUCT_NOT_EXIST = 'PRODUCT_NOT_EXIST';
        const PRODUCT_NOT_AVAILABLE = 'PRODUCT_NOT_AVAILABLE';
	const PRODUCT_AVAILABLE_CACHE_NOT_EXIST = 'PRODUCT_AVAILABLE_CACHE_NOT_EXIST';
        
        const PRODUCT_INFO_NOT_EXIST = "PRODUCT_INFO_NOT_EXIST";
        const REQUEST_IS_NOT_DIY = "REQUEST_IS_NOT_DIY";
        
        const CAPTCHA_NOT_CORRECT = "CAPTCHA_NOT_CORRECT";
}