<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Product\Module'                        => __DIR__ . '/Module.php',
    'Product\Controller\ListController' => __DIR__ . '/src/Product/Controller/ListController.php',
);
