<!--轮廓图-->
<style type="text/css">
    /* 本例子css */
    .fullSlide{ width:100%;  position:relative;  min-height:410px; background:#000;  }
    .fullSlide .bd{ margin:0; position:relative; z-index:0; overflow:hidden;  }
    .fullSlide .bd ul{ width:100% !important; margin-bottom: 0; }
    .fullSlide .bd li{ width:100% !important;  min-height:410px; overflow:hidden; text-align:center;  }
    .fullSlide .bd li a{ display:block; min-height:410px; }

    .fullSlide .prev,
    .fullSlide .next{  display:block;  position:absolute; z-index:1; top:50%; margin-top:-30px; left:15%;  z-index:1; width:90px; height:90px; background:url(http://cdn.xiyouus.com/img/jianzuo.png) no-repeat;  cursor:pointer; filter:alpha(opacity=50);opacity:0.5; display:none;  }
    .fullSlide .next{ left:auto; right:15%;background:url(http://cdn.xiyouus.com/img/jianyou.png) no-repeat;}

</style>
<div class="fullSlide">
    <div class="bd">
        <ul>
            <?php 
                $herosliderLink = $config['index_page']['heroslider'];
                $hcnt = 1;
                foreach($herosliderLink as $aheroslide){
                    echo '<li _src="url(/img/product/index/heroslide'.$hcnt.'.jpg)" style="background:#c0c0c0 center 0 no-repeat;"><a target="_blank" href="'.$aheroslide.'"></a></li>';
                    $hcnt++;
                }
            ?>
        </ul>
    </div>
    <span class="prev"></span>
    <span class="next"></span>
</div>
<!--轮廓图-->
<!--中部-->
<div class="wai">
    <div class="dang">
        <ul class="yiyou">
            <li>
                <div class="tangseng"><img src="img/tangsenghead.png" width="120" height="120"></div>
                <div class="service"><?php echo htmlspecialchars($config['index_page']['promo_line'][0]);?></div>
            </li>
            <li>
                <div class="wukong"><img src="img/wukonghead.png" width="120" height="120"></div>
                <div class="diyservice"><?php echo htmlspecialchars($config['index_page']['promo_line'][1]);?></div>
            </li>       
            <li>
                <div class="bajie"><img src="img/bajiehead.png" width="120" height="120"></div>
                <div class="localservice"><?php echo htmlspecialchars($config['index_page']['promo_line'][2]);?></div>
            </li>
            <li>
                <div class="shaseng"><img src="img/shasenghead.png" width="120" height="120"></div>
                <div class="countries"><?php echo htmlspecialchars($config['index_page']['promo_line'][3]);?></div>
            </li>
        </ul>
        <?php
        //TODO design this part!
//        <!--		<div class="zuji clearfix">
//                                <div class="jkdf">
//                                        <ul class="zhuanshu">
//                                                <li>您的足迹，您的世界</li>
//                                        </ul>
//                                        <ul class="banzi">
//                                                <li><div class="half">半自助游</div></li>
//                                                <li><div class="pure">纯自助游</div></li>
//                                        </ul>
//                                        <ul class="dangdi">
//                                                <li><a href="http://dev.xiyouus.com/product/query/diy/1?mode=2">当地参团</a></li>
//                                                <li><a href="">WWOOF</a></li>
//                                                <li><a href="">特色项目</a></li>
//                                                <li><a href="">深度玩法</a></li>
//                                        </ul>
//                                </div>
//                                <div class="DIY">
//                                        <ul class="ziding">我的DIY</ul>
//                                        
//                                </div>
//                        </div>-->
        ?>
    </div>

    <?php
    //Generate promo section
    $promo_sect = $config['index_page']['promo_sect'];
    foreach ($promo_sect as $a_promo_sect) {
        echo '<div class="beijing">
            <div class="meizhou">
                <div class="wuti">';
        echo $a_promo_sect['sect_title'];
        echo '</div></div>
            <div class="tuan">
                <div class="goubu">';
        $hero_id = $a_promo_sect['hero_promo']['product_id'];
        echo '<div class="hai"><a href="/product/query/detail/'.$hero_id.'"><img src="/img/product/'.$hero_id.'/1.jpg" height="400px" width="320px"></a></div>';
        if(isset($a_promo_sect['hero_promo']['promo_line']) && strlen($a_promo_sect['hero_promo']['promo_line'])){
            //use customized promotion line
            $hero_promo_line = $a_promo_sect['hero_promo']['promo_line'];
        }else{
            $hero_promo_line = $product[$hero_id]['title'];
        }
        echo '<div class="daoguo"><a href="/product/query/detail/'.$hero_id.'">'.$hero_promo_line.'</a></div>';
        echo '</div>
                <ul class="miaoyou">';
        $cnt = 0;
        foreach($a_promo_sect['promo'] as $a_product){
            $promo_id = $a_product['product_id'];
            if(isset($a_product['promo_line']) && strlen($a_product['promo_line'])){
                //use customized promotion line
                $promo_line = $a_product['promo_line'];
            }else{
                $promo_line = $product[$promo_id]['title'];
            }
            if($cnt < 3){
                echo '<li style="margin-top:0;">';
            }else{
                echo '<li>';
            }
            echo  '<div class="zidji"><a href="/product/query/detail/'.$promo_id.'"><img src="/img/product/'.$promo_id.'/thumb.jpg" width="270px" height="180px"></a></div>';
            echo '<div class = "lagong"><a href = "/product/query/detail/'.$promo_id.'">'.$promo_line.'</a></div>';
            echo '</li>';
            $cnt++;
        }
        echo '</ul></div></div>';
    }
//    <div class="beijing">
//        <div class="meizhou">
//            <div class="wuti">每周团购</div>
//            <!--<div class="danzi"><a href="">更多 > ></a></div>-->
//        </div>
//        <div class="tuan">
//            <div class="goubu">
//                <div class="hai"><a href=""><img src="http://cdn.xiyouus.com/img/haidao.jpg"></a></div>
//                <!--<div class="shale"><img src="http://cdn.xiyouus.com/img/miaosha.png"></div>-->
//                <div class="daoguo"><a href="">【品味欧洲】欧洲五国九日游</a></div>
//            </div>
//            <ul class="miaoyou">
//    <li style = "margin-top:0;">
//    <div class = "zidji"><a href = ""><img src = "http://cdn.xiyouus.com/img/budala.png"></a></div>
//    <!--<div class = "buda"><img src = "http://cdn.xiyouus.com/img/miaosha.png"></div> -->
//    <div class = "lagong"><a href = "">【品味欧洲】欧洲五国九日游</a></div>
//    </li>
//    <li style = "margin-top:0;">
//    <div class = "zidji"><a href = ""><img src = "http://cdn.xiyouus.com/img/budala.png"></a></div>
//    <!--<div class = "buda"><img src = "http://cdn.xiyouus.com/img/miaosha.png"></div> -->
//    <div class = "lagong"><a href = "">【品味欧洲】欧洲五国九日游</a></div>
//    </li>
//    <li style = "margin-top:0;">
//    <div class = "zidji"><a href = ""><img src = "http://cdn.xiyouus.com/img/budala.png"></a></div>
//    <!--<div class = "buda"><img src = "http://cdn.xiyouus.com/img/miaosha.png"></div> -->
//    <div class = "lagong"><a href = "">【品味欧洲】欧洲五国九日游</a></div>
//    </li>
//    <li>
//    <div class = "zidji"><a href = ""><img src = "http://cdn.xiyouus.com/img/budala.png"></a></div>
//    <!--<div class = "buda"><img src = "http://cdn.xiyouus.com/img/miaosha.png"></div> -->
//    <div class = "lagong"><a href = "">【品味欧洲】欧洲五国九日游</a></div>
//    </li>
//    <li>
//    <div class = "zidji"><a href = ""><img src = "http://cdn.xiyouus.com/img/budala.png"></a></div>
//    <!--<div class = "buda"><img src = "http://cdn.xiyouus.com/img/miaosha.png"></div> -->
//    <div class = "lagong"><a href = "">【品味欧洲】欧洲五国九日游</a></div>
//    </li>
//    <li>
//    <div class = "zidji"><a href = ""><img src = "http://cdn.xiyouus.com/img/budala.png"></a></div>
//    <!--<div class = "buda"><img src = "http://cdn.xiyouus.com/img/miaosha.png"></div> -->
//    <div class = "lagong"><a href = "">【品味欧洲】欧洲五国九日游</a></div>
//    </li>
//    </ul>
//    </div>
//    </div>
    ?>

    <?php
//    <!--	<div class="jingchang">
//                    <div class="meizhou">
//                            <div class="wuti">西游攻略</div>
//                    </div>
//                    <ul class="xiang clearfix">
//                            <li class="qingdao">
//                                    <div class="xiamen"><a href=""><img src="http://cdn.xiyouus.com/img/xianggang.jpg"></a></div>
//                                    <div class="ziti">更新时间：2014-07-02</div>
//                                    <div class="xiazai"><a href="">1234567人下载</a></div>
//                            </li>
//                            <li class="qingdao">
//                                    <div class="xiamen"><a href=""><img src="http://cdn.xiyouus.com/img/xianggang.jpg"></a></div>
//                                    <div class="ziti">更新时间：2014-07-02</div>
//                                    <div class="xiazai"><a href="">1234567人下载</a></div>
//                            </li>
//                            <li class="qingdao">
//                                    <div class="xiamen"><a href=""><img src="http://cdn.xiyouus.com/img/xianggang.jpg"></a></div>
//                                    <div class="ziti">更新时间：2014-07-02</div>
//                                    <div class="xiazai"><a href="">1234567人下载</a></div>
//                            </li>
//                            <li class="qingdao">
//                                    <div class="xiamen"><a href=""><img src="http://cdn.xiyouus.com/img/xianggang.jpg"></a></div>
//                                    <div class="ziti">更新时间：2014-07-02</div>
//                                    <div class="xiazai"><a href="">1234567人下载</a></div>
//                            </li>
//                            <li class="qingdao">
//                                    <div class="xiamen"><a href=""><img src="http://cdn.xiyouus.com/img/xianggang.jpg"></a></div>
//                                    <div class="ziti">更新时间：2014-07-02</div>
//                                    <div class="xiazai"><a href="">1234567人下载</a></div>
//                            </li>
//                            <li class="qingdao">
//                                    <div class="xiamen"><a href=""><img src="http://cdn.xiyouus.com/img/xianggang.jpg"></a></div>
//                                    <div class="ziti">更新时间：2014-07-02</div>
//                                    <div class="xiazai"><a href="">1234567人下载</a></div>
//                            </li>
//                    </ul>
//            </div>-->
    ?>
    <?php
//    <!--	<div class="jingchang">
//                    <div class="meizhou">
//                            <div class="wuti">西游DIY</div>
//                    </div>
//                    
//            </div>-->
    ?>
    
    <?php 
        $showcase_sects = $config['index_page']['product_showcase'];
        foreach($showcase_sects as $a_showcase_sect){
            echo '<div class="maridaifu clearfix"><div class="meizhou"><div class="wuti">' . $a_showcase_sect['sect_title'].'</div></div>';
            echo '<ul class="jah clearfix">';
            
            foreach($a_showcase_sect['product'] as $a_product){
                $product_id = $a_product['product_id'];
                if(isset($a_product['promo_line']) && strlen($a_product['promo_line'])){
                    $promo_line = $a_product['promo_line'];
                }else{
                    $promo_line = $product[$product_id]['title'];
                }
                
                echo '<li class="liagn">
                        <div class="yao">
                            <div class="tu"><a href="/product/query/detail/'.$product_id.'"><img src="/img/product/'.$product_id.'/thumb.jpg" width="260px" height="160px"></a></div>
                            <div class="nid">
                                <a href="/product/query/detail/'.$product_id.'"><div class="daifu">'.$promo_line.'</div>
                                <div class="shehua">'.$product[$product_id]['abstract'].'</div></a>
                            </div>
                        </div>
                    </li>';
            }
            
            echo '</ul>';
            echo '</div>';//maridaifu
        }
        
        
//    <div class="maridaifu clearfix">
//        <div class="meizhou">
//            <div class="wuti">美西旅行</div>
//        </div>
//        <ul class="jah clearfix">
//            <li class="liagn">
//                <div class="yao">
//                    <div class="tu"><img src="http://cdn.xiyouus.com/img/maridaifu.jpg"></div>
//                    <div class="nid">
//                        <div class="daifu">马尔代夫伊露岛</div>
//                        <div class="shehua">这个奢华的休息场所适合那些喜欢去度假，远离公众视线，有私人沙滩和接贵宾用的豪华船只，这一休息场所有超过两层楼的私人别墅，拥有三个卧室。 主卧有自己的私人泳池，带有封闭的花园浴室，三个洗浴室，一个台球室，一个健身房，一个封闭式花园有一个私人的游泳池，甲板，草坪，丰富</div>
//                    </div>
//                    <div class="xiaotu"><img src="http://cdn.xiyouus.com/img/tese.png"></div>
//                </div>
//            </li>
//            <li class="liagn">
//                <div class="yao">
//                    <div class="tu"><img src="http://cdn.xiyouus.com/img/maridaifu.jpg"></div>
//                    <div class="nid">
//                        <div class="daifu">马尔代夫伊露岛</div>
//                        <div class="shehua">这个奢华的休息场所适合那些喜欢去度假，远离公众视线，有私人沙滩和接贵宾用的豪华船只，这一休息场所有超过两层楼的私人别墅，拥有三个卧室。 主卧有自己的私人泳池，带有封闭的花园浴室，三个洗浴室，一个台球室，一个健身房，一个封闭式花园有一个私人的游泳池，甲板，草坪，丰富</div>
//                    </div>
//                    <div class="xiaotu"><img src="http://cdn.xiyouus.com/img/tese.png"></div>
//                </div>
//            </li>
//            <li class="liagn">
//               <div class="yao">
//                    <div class="tu"><img src="http://cdn.xiyouus.com/img/maridaifu.jpg"></div>
//                    <div class="nid">
//                        <div class="daifu">马尔代夫伊露岛</div>
//                        <div class="shehua">这个奢华的休息场所适合那些喜欢去度假，远离公众视线，有私人沙滩和接贵宾用的豪华船只，这一休息场所有超过两层楼的私人别墅，拥有三个卧室。 主卧有自己的私人泳池，带有封闭的花园浴室，三个洗浴室，一个台球室，一个健身房，一个封闭式花园有一个私人的游泳池，甲板，草坪，丰富</div>
//                    </div>
//                    <div class="xiaotu"><img src="http://cdn.xiyouus.com/img/tese.png"></div>
//                </div>
//            </li>
//            <li class="liagn">
//                <div class="yao">
//                    <div class="tu"><img src="http://cdn.xiyouus.com/img/maridaifu.jpg"></div>
//                    <div class="nid">
//                        <div class="daifu">马尔代夫伊露岛</div>
//                        <div class="shehua">这个奢华的休息场所适合那些喜欢去度假，远离公众视线，有私人沙滩和接贵宾用的豪华船只，这一休息场所有超过两层楼的私人别墅，拥有三个卧室。 主卧有自己的私人泳池，带有封闭的花园浴室，三个洗浴室，一个台球室，一个健身房，一个封闭式花园有一个私人的游泳池，甲板，草坪，丰富</div>
//                    </div>
//                    <div class="xiaotu"><img src="http://cdn.xiyouus.com/img/tese.png"></div>
//                </div>
//            </li>
//        </ul>
//    </div>
    ?>
</div>
<!--中部-->
<script src="/js/jquery.SuperSlide.2.1.1.js"></script>
<script type="text/javascript">
    /* 控制左右按钮显示 */
    jQuery(".fullSlide").hover(function() {
        jQuery(this).find(".prev,.next").stop(true, true).fadeTo("show", 0.5)
    }, function() {
        jQuery(this).find(".prev,.next").fadeOut()
    });
    var slideWidth = 1600;
    var slideHeight = 410;
    var sWTosH = slideWidth/slideHeight;
    /* 调用SuperSlide */
    jQuery(".fullSlide").slide({titCell: ".hd ul", mainCell: ".bd ul", effect: "fold", autoPlay: true, autoPage: true, trigger: "click",
        startFun: function(i) {
            var curUl = jQuery(".fullSlide .bd ul");
            var curLi = jQuery(".fullSlide .bd li").eq(i); /* 当前大图的li */
            var curLia = jQuery(".fullSlide .bd li a").eq(i); /* 当前大图的li */
            if (!!curLi.attr("_src")) {
                var w = screen.width;
                var h = curLi.height();
                var hR = slideHeight;
                var wR = slideWidth;
                if(w>slideWidth){
                    wR = w;
                    hR = wR/sWTosH;
                }
                if(h> hR){
                    hR = h;
                    wR = hR * sWTosH;
                }  
                curLi.width(screen.width);
                curLi.height(hR);
                curLia.height(hR);
                curUl.height(hR);
                curLi.css({
                    "height": hR,
                    //TODO: need to handle resizing
                    "background-image": curLi.attr("_src"),
                    "background-position" : "center", 
//                    "background-attachment": "fixed",
                    "background-size": wR + "px " + hR + "px"
                });
                curLi.removeAttr("_src") /* 将_src地址赋予li背景，然后删除_src */
            }
        }
    });
</script>
