<!--中部-->
<link href="http://static.qyer.com/min/?version=1411981335&b=css&f=common/jquery.ui.datepicker.css,common/base.css,common/headfoot.css,common/tpl.css,plan2/index.css" rel="stylesheet" type="text/css" media="screen"
<body id="body">
<div style="display:none;"><img src="http://static.qyer.com/images/plan2/index/ind_2000x576.jpg"></div>
<div class="pl_index_banner">
	<div class="layer">
    	<div class="title" title="Your Perfect Trip"></div>
        <div class="button">
            
        	<li target="_blank" onblur="this.blur();" class="found_small" title="Create My Trip" data-bn-ipg="planhome-createplan"></li>
            <li class="my_plan" title="My Trip Plan" data-bn-ipg="planhome-mine"></li>
                        
        </div>
    </div>
    <div class="sline">
    	<a href="javascript:;" title="Search Trip" data-bn-ipg="planhome-searchplan"></a>
    </div>
</div>

<div class="pl_index_rec">
	<div class="layer">
		<div class="title"><span title="Why Us"></span></div>
    </div>
</div>
</body>

<!--中部-->
<script src="/js/jquery.SuperSlide.2.1.1.js"></script>
<script type="text/javascript">
    /* 控制左右按钮显示 */
    jQuery(".fullSlide").hover(function() {
        jQuery(this).find(".prev,.next").stop(true, true).fadeTo("show", 0.5)
    }, function() {
        jQuery(this).find(".prev,.next").fadeOut()
    });
    var slideWidth = 1600;
    var slideHeight = 410;
    var sWTosH = slideWidth/slideHeight;
    /* 调用SuperSlide */
    jQuery(".fullSlide").slide({titCell: ".hd ul", mainCell: ".bd ul", effect: "fold", autoPlay: true, autoPage: true, trigger: "click",
        startFun: function(i) {
            var curUl = jQuery(".fullSlide .bd ul");
            var curLi = jQuery(".fullSlide .bd li").eq(i); /* 当前大图的li */
            var curLia = jQuery(".fullSlide .bd li a").eq(i); /* 当前大图的li */
            if (!!curLi.attr("_src")) {
                var w = screen.width;
                var h = curLi.height();
                var hR = slideHeight;
                var wR = slideWidth;
                if(w>slideWidth){
                    wR = w;
                    hR = wR/sWTosH;
                }
                if(h> hR){
                    hR = h;
                    wR = hR * sWTosH;
                }  
                curLi.width(screen.width);
                curLi.height(hR);
                curLia.height(hR);
                curUl.height(hR);
                curLi.css({
                    "height": hR,
                    //TODO: need to handle resizing
                    "background-image": curLi.attr("_src"),
                    "background-position" : "center", 
//                    "background-attachment": "fixed",
                    "background-size": wR + "px " + hR + "px"
                });
                curLi.removeAttr("_src") /* 将_src地址赋予li背景，然后删除_src */
            }
        }
    });
</script>
