<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'Mail\Module'               => __DIR__ . '/Module.php',
  'Mail\Mail\MailService'     => __DIR__ . '/src/Mail/Mail/MailService.php',
  'Mail\Service\Factory\Mail' => __DIR__ . '/src/Mail/Service/Factory/Mail.php',
);
